name: Run TorchBench with Inductor

on:
  push:
    tags:
      - ciflow/inductor/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.8"
  # must be consistent with https://github.com/pytorch/benchmark/blob/main/requirements.txt#L19
  NUMPY_VERSION: "1.21.2"
  PR_NUM: ${{ github.event.number }}
  PR_BODY: ${{ github.event.pull_request.body }}
  PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
  PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_OSSCI_METRICS_V2_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_OSSCI_METRICS_V2_SECRET_ACCESS_KEY }}

jobs:
  run-torchbench-with-inductor:
    if: ${{ github.repository_owner == 'pytorch' }}
    runs-on: [self-hosted, a100-runner]
    # Set to 12 hours
    timeout-minutes: 720
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
      #- name: Setup Linux
      #  uses: ./.github/actions/setup-linux
      - name: Setup SSH (Click me for login details)
        uses: pytorch/test-infra/.github/actions/setup-ssh@main
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}
      - name: Create conda environment and install deps
        run: |
          conda create -y -n pr-ci python="${PYTHON_VERSION}"
          # shellcheck disable=SC1091
          . "${HOME}"/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          # pin cmake version to 3.22 since 3.23 breaks pytorch build
          # see details at: https://github.com/pytorch/pytorch/issues/74985
          conda install -y numpy="${NUMPY_VERSION}" requests ninja pyyaml mkl mkl-include \
                           setuptools cmake=3.22 cffi typing_extensions boto3 \
                           future six dataclasses pillow pytest tabulate gitpython git-lfs tqdm psutil
          conda install -y -c pytorch magma-cuda116
      - name: Build PyTorch
        run: |
          # shellcheck disable=SC1091
          . "${HOME}"/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          USE_MKL=0 .jenkins/pytorch/build.sh
      - name: Checkout TorchBench
        uses: actions/checkout@v3
        with:
          path: benchmark
          # Pin to specific version to avoid upstream breakages
          ref: 24b95f2f627bf07a61cefed653419389a7586357
      - name: Install TorchBench
        run: |
          # shellcheck disable=SC1091
          . "${HOME}"/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          pushd torchbenchmark
          pip3 install --pre torchtext torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
          python install.py
          pip install gym==0.25.2  # workaround issue in 0.26.0
          popd
      - name: Run TorchBench
        run: |
          # shellcheck disable=SC1091
          . "${HOME}"/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          # Testing with --only resnet18 for now
          python3 benchmarks/dynamo/torchbench.py \
                  --ci --accuracy --skip-accuracy-check -d cuda \
                  --inductor --training --float32 \
                  --only resnet18 \
                  --output=indcutor_torchbench_training.csv
      - name: TorchBench result check
        run: |
          . "${HOME}"/miniconda3/etc/profile.d/conda.sh
          conda activate pr-ci
          python benchmarks/dynamo/check_csv.py -f indcutor_torchbench_training.csv
      - name: Remove conda environment and cleanup
        run: |
          conda env remove --name pr-ci
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: TorchBench Running with Inductor result
          path: pytorch/indcutor_torchbench_training.csv
